{% set name = "mp-pyrho" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6705a9fd4cdb01435bd9f0884f5a1ac9289cf2b6bd3caf288653c96afc90bba4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - versioningit
  run:
    - python >=3.9
    - pymatgen >=2023.9.21

test:
  imports:
    - pyrho

about:
  home: https://github.com/materialsproject/pyrho
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE
  summary: Tools for re-griding volumetric quantum chemistry data for machine-learning purposes
  doc_url: https://materialsproject.github.io/pyrho/
  dev_url: https://github.com/materialsproject/pyrho

extra:
  recipe-maintainers:
    - njzjz
